package(
    default_visibility = [
        "//visibility:public",
    ],
)

cc_library(
    name = "chre_api",
    hdrs = [
        "include/chre_api/chre.h",
        "include/chre_api/chre/common.h",
        "include/chre_api/chre/event.h",
        "include/chre_api/chre/gnss.h",
        "include/chre_api/chre/nanoapp.h",
        "include/chre_api/chre/re.h",
        "include/chre_api/chre/sensor.h",
        "include/chre_api/chre/version.h",
        "include/chre_api/chre/wifi.h",
        "include/chre_api/chre/wwan.h",
    ],
    includes = [
        "include",
        "include/chre_api",
    ],
)
