package(
    default_visibility = [
        "//visibility:public",
    ],
)

cc_library(
    name = "pal",
    hdrs = [
        "include/chre/pal/gnss.h",
        "include/chre/pal/version.h",
        "include/chre/pal/wifi.h",
        "include/chre/pal/wwan.h",
    ],
    includes = [
        "include",
    ],
    deps = [
        "//chre_api:chre_api",
    ],
)
